### ISSUE TITLE
No backup on first install

### ISSUE THREAD

**Issue by zero2one** [druleton/druleton#3]
When a project is installed for the first time, an error is shown because of a failing backup.

```
Create backup (can take a while...)
tar: web: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
 ✗ Can not backup web directory.
Unable to load class Drush\Sql\Sql                                                                                                                         [error]
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in              [error]
/usr/local/src/drush/commands/sql/sql.drush.inc:595
Stack trace:
#0 /usr/local/src/drush/commands/sql/sql.drush.inc(274): drush_sql_get_class()
#1 [internal function]: drush_sql_dump()
#2 /usr/local/src/drush/includes/command.inc(368): call_user_func_array('drush_sql_dump', Array)
#3 /usr/local/src/drush/includes/command.inc(219): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /usr/local/src/drush/includes/command.inc(187): call_user_func_array('drush_command', Array)
#6 /usr/local/src/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 /usr/local/src/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /usr/local/src/drush/drush.php(11): drush_main()
#9 {main}
 ✗ Can not backup database.
```

Check first if there is something to backup before calling the backup function.

**Comment by zero2one** [comment]
Fix is included in release 0.1.0
